### ISSUE TITLE
Theme doesn't work with the new Steam library [Linux]

### ISSUE THREAD

**Issue by Urimu** [dracula/steam#10]
I know that there was this issue already (https://github.com/dracula/steam/issues/7), but it still does not work. At least not fully, some parts are changed, and maybe the background color is the right one but everything else is the same as default.

Here are some screen shots: https://waifupaste.moe/raw/AF.png https://waifupaste.moe/raw/agJ.png

Thank you!

\* I just noticed that the pink highlight which should be on selected item can be seen for a brief moment, when I hover over the top menus but it disappears almost instantly

**Comment by Trollwut** [comment]
yes, for now there are not too many deviations for Dracula, except for the highlight colors :)

@tintinmaster rebuilt it from the ground up totally new, so he might have some more ideas.

**Comment by tintinmaster** [comment]
Steam has made it harder to customize it.
To change the design of the new library, you can't do it the normal theme way.
You have to replace the default .css file (extend and overwrite) in the main steam folder. The changes only persist, if Steam is started in -noverifyfiles mode and is only persistent until the next steam update, where the files are verified.

I have tried out some css settings and at least got the game list on the left to have the theme, but I'm not sure if the game overview window can be altered.

I planned to extend the theme with the .css file and also to write a script to do the exchange, so it can be easy "fixed" after an update, but currently I'm writing my exams so you have to wait at least a month to get any results. :)

**Comment by Urimu** [comment]
> Steam has made it harder to customize it.
> To change the design of the new library, you can't do it the normal theme way.
> You have to replace the default .css file (extend and overwrite) in the main steam folder. The changes only persist, if Steam is started in -noverifyfiles mode and is only persistent until the next steam update, where the files are verified.

That sucks. I have some free time, so I might look in to it, but I can't promise anything.

**Comment by NicTanghe** [comment]
Same issue on Windows,
2 bad

**Comment by tintinmaster** [comment]
![image](https://user-images.githubusercontent.com/36089973/88699247-62283580-d107-11ea-8d0c-1836d244da01.png)
I made some progress with the .css file for the library. It's still not finished, hover and selected mode is missing. You can check it out on my fork. If you have any improvents or wishes for style options let me know. :sunglasses:

**Comment by tintinmaster** [comment]
I think i finalized the layout for the game list. There still could be some errors, time and testing will tell.

To try it out and help finding errors or room to improvement, check out my [fork](https://github.com/tintinmaster/steam) 
You can also check if the install script (execute cssInstall.sh) in the scripts folder works (did not test on Windows).

To "install" it manually rename the `libraryroot.css` to `steamlibraryroot.css` in the `steam/steamui/css` folder and copy both css from the skin folder into it. 

To keep this .css you have to start steam always in `-noverifyfiles` mode

P.S. I'm still trying to figure out if the individual game pages or the collections pages can be customized.

**Comment by tintinmaster** [comment]
![image](https://user-images.githubusercontent.com/36089973/88729164-87cb3400-d133-11ea-85e0-00e9c14c3f81.png)
![image](https://user-images.githubusercontent.com/36089973/88729180-8e59ab80-d133-11ea-869b-f94fb6b68d7c.png)

I think it is mostly completed. Theres problably still many things wrong. :sweat_smile: But it looks very promising.
Now I need **your** assistance in testing it an providing feedback to improve it.


Tomorrow I will improve installation instructions and scripts, so it is easier to install for the average user.

**Comment by Trollwut** [comment]
> To "install" it manually rename the `libraryroot.css` to `steamlibraryroot.css` in the `steam/steamui/css` folder and copy both css from the skin folder into it.
> 
> To keep this .css you have to start steam always in `-noverifyfiles` mode

Running it without the flag would end in a resetted theme?

Or is there any way to have the theme files by themselves and being used, without losing them on an update?

**Comment by NicTanghe** [comment]
Yeah for me the whole thing is bugged.
[image: UneKxGAH08.png]

Op wo 29 jul. 2020 om 02:14 schreef Trollwut <notifications@github.com>:

**Comment by tintinmaster** [comment]
> Running it without the flag would end in a resetted theme?

Yes, because Steam would recognize an altered file and would replace it. But when Steam updates, the theme gets reset nevertheless. 

> Or is there any way to have the theme files by themselves and being used, without losing them on an update?

Years ago, you could have a custom.css file in a skins folder and steam would recognize it, unfortanely this is not the case anymore and you have to replace the original ones. (I found no other way by searching through forums :disappointed: )

> And to add: Love your progress!

Thankyou <3

**Comment by tintinmaster** [comment]
> Yeah for me the whole thing is bugged. [image: UneKxGAH08.png] 

I can't see the picture, could you upload it directly here on github or on another platform.
And which os are you using and did you use the script or manual "install"?

**Comment by NicTanghe** [comment]
I am using Windows 10 and used the manual install,
i Could never figure out how to post images on GitHub (aside from in the
description)

So i`m confused bout how to post pictures in issues comment section.

Op wo 29 jul. 2020 om 08:39 schreef Tim Schneider <notifications@github.com

**Comment by tintinmaster** [comment]
@NicTanghe I just checked on my Windows Installation and everything worked fine for me.
Maybe my Instructions were a bit unclear? 
Before installation there should be a css file called `libraryroot` in `steam\steamui\css\`. This file must be renamed to exactly `steamlibraryroot`. Now you copy the css files `custom` and `libraryroot` from your dracula theme installation (`steam\skins\dracula\css\ `) into `steam\steamui\css\`. Now the library should have the theme applied. 

I don't know if you can post pictures with an email reply, but on the website you can just drag&drop files into the text field and it will be uploaded.

**Comment by Urimu** [comment]
Nice progress! I didn't have the time to look at this myself, but it's looking good! Tried your fork just now and the library looks as it should, just the top of the "category selection" in settings is bit wonky, see img:

**Comment by tintinmaster** [comment]
@Urimu Are you sure you set the skin in the Interface Settings? Because in the Screenshot there is nothing visible of the theme. 
And the Remote Play Section should have been messed up, when you used by fork, because I forgot to merge it in my own fork too. 
See #11

**Comment by Urimu** [comment]
@tintinmaster Sorry for the late reply. I didn't set the skin in steam settings, I just did the manual install and started steam. Now that I selected it, the sections are broken (the remote play and shader pre-caching) everything else looks fine.

**Comment by tintinmaster** [comment]
@Urimu Try downloading it again. I pushed a fix for it

**Comment by Urimu** [comment]
@tintinmaster Ok, I just got a Steam update and the theme didn't get overwritten back to default. I will download the fix now.

**Comment by Urimu** [comment]
Just found out that the download graphs are back to default colors.
#
![2020-07-31--22:39:40](https://user-images.githubusercontent.com/46381898/89075403-6c079e00-d37e-11ea-9020-90614a850b85.png)

**Comment by tintinmaster** [comment]
@Urimu Thx for pointing this out, I think i deleted the wrong files. I will look into it.

**Comment by tintinmaster** [comment]
Added the files back, should be fixed now :)

**Comment by Urimu** [comment]
Sorry for the late, late reply. It is indeed fixed :) Thank you!

**Comment by KrossGasistaMatriculado** [comment]
hi does this work on any steam skin? because I wanna use it with pixelvision2
and if I mess up how can I fix it?

**Comment by tintinmaster** [comment]
@KrossGasistaMatriculado You can modify the css files to your liking to represent pixelvision2. I don't know if pixelvision had css files that would achieve it, since recently Valve decided to change the names and functions of the css files. 

If you mess up, just delete your css folder of Steam and start Steam in normal mode. Steam will redownload the missing files.
