### ISSUE TITLE
2 Broken Sections in Settings [LINUX]

### ISSUE THREAD

**Issue by TimeFreeze1337** [dracula/steam#11]
In the Settings there are 2 Sections which are broken as you can see in the screenshots. 

![Screenshot_2020-07-29_12-17-44](https://user-images.githubusercontent.com/59339523/88788519-b8dc5080-d195-11ea-9bbd-70e707f065c9.png)
![Screenshot_2020-07-29_12-18-22](https://user-images.githubusercontent.com/59339523/88788521-ba0d7d80-d195-11ea-8616-ff74303a5e53.png)

**Comment by tintinmaster** [comment]
Can reproduce, will look into it.
