### ISSUE TITLE
Readme not clear

### ISSUE THREAD

**Issue by SimoneLeoni1987** [dracula/steam#14]
rename libraryroot.css in Steam/steamui/css to steamlibraryroot.css
move both .css files from this skin into this folder

"Both .css files", you said to rename ONE file, why are you referring to two files?

It's not clear

**Comment by GabLeRoux** [comment]
```bash
cd Steam/steamui/css
mv libraryroot.css steamlibraryroot.css
git clone https://github.com/dracula/steam.git dracula_steam_temp
cp dracula_steam_temp/css/*.css ./
rm -rf dracula_steam_temp
```

**Comment by tintinmaster** [comment]
With "Both .css files from this skin" I meant the two files provided with this skin (`custom.css` and `libraryroot.css`) found in `dracula/css`
