### ISSUE TITLE
Add @tintinmaster as a team member

### ISSUE THREAD

**Issue by Trollwut** [dracula/steam#16]
Hey @zenorocha !

Created a discussion in Dracula's Steam group. As I'm just a member there, I can't add him directly to the team.

What would be the process to add him? I could add him directly to the repo, but I guess as we have a team, it's intended to be used.

@tintinmaster added most of the new style stuff, so he really earned to also maintain this repo.

**Comment by zenorocha** [comment]
I just invited @ tintinmaster to the Steam team. Thanks for your patience.
