### ISSUE TITLE
not working on steam

### ISSUE THREAD

**Issue by sarcasticdrank** [dracula/steam#19]
i went to do the extended install and it's not working. i follow all of the steps it says to, rename everything, and the games tab still isn't skinned. im on windows.

**Comment by tintinmaster** [comment]
So the library is not working?

Can you send me screenshots of your `Steam/steamui/css` folder?

**Comment by sarcasticdrank** [comment]
![Screenshot 2021-01-15 153625](https://user-images.githubusercontent.com/55339451/104776077-7b6d7e80-5747-11eb-8abf-fd7b9913bcb9.png)

here is what i have

**Comment by tintinmaster** [comment]
I will look into it, it looks like steam updated their `.css` files and their names :thinking:

**Comment by sarcasticdrank** [comment]
thank you!

**Comment by tintinmaster** [comment]
I just pushed a new version with #20 .
Just download it again and follow the new install instructions.

It will take a day or so until its visible on the website, so i just post them here again:

1. rename 5.css in Steam/steamui/css to steam5.css
2. move both .css files (custom.css & 5.css) from the skin folder into the css folder of steam
3. if you start Steam per autostart, check how to alter the autostart instructions in your OS and add the start option -noverifyfiles
