### ISSUE TITLE
Only partial Skin

### ISSUE THREAD

**Issue by Rovetown** [dracula/steam#21]
For me when installing the Theme, only the announcements button gets the color, and the rest of the UI seems to look like it should, but with less color I believe. Library and Store, as well as font and font color looks like default steam. I did it the normal installation way, didn't work. did the extended installation method, didn't work either. At least I've got a new Button saying: Dracula with the Subtabs **Report Bug** and **Theme Version 210116**.

Here's a Picture of my Game's List.
![Screenshot 2021-05-17 102511](https://user-images.githubusercontent.com/42076598/118457642-40ca2180-b6fa-11eb-8405-74e437793926.png)

**Comment by tintinmaster** [comment]
Hmm, it looks steam is changing the names of the .css files again.
But it is still working for me, could you send a screenshot of your `C:\Program Files\Steam\steamui\css` folder?
It should contain files named `5.css`, `steam5.css` and `custom.css`

**Comment by Rovetown** [comment]
![Screenshot 2021-05-17 115737](https://user-images.githubusercontent.com/42076598/118470569-16329580-b707-11eb-8342-8373790d67da.png)

**Comment by Rovetown** [comment]
Man sieht, dass die custom.css fehlt oder umbenannt wurde

**Comment by Rovetown** [comment]
![Screenshot 2021-05-17 162437](https://user-images.githubusercontent.com/42076598/118505118-6a9c3c00-b72c-11eb-9d32-21b37f5fdaf8.png)

**Comment by Rovetown** [comment]
Hier ist der richtige Screenshot.

**Comment by tintinmaster** [comment]
Interessant ist, dass `5.css` leer aussieht. Kann es sein das da irgendwas schiefgelaufen ist beim kopieren?
In dieser Datei müssten folgende beide Zeilen drinstehen:
```
@import 'steam5.css';
@import 'custom.css';
```
Falls das nicht funktioniert schaue ich die Tage mal, was Steam jetzt wieder vorhat mit den Namen.

**Comment by Rovetown** [comment]
Tatsächlich ist 5.css nicht leer, aber steam5.css und 5.css haben den selben Inhalt, keines davon hat die import statements. Hab das nun manuell ersetzt und es geht jetzt. Anscheinend muss man diese Schritte machen:

- rename 5.css in Steam/steamui/css to steam5.css
- move both .css files (custom.css & 5.css) from the skin folder into the css folder of steam

da es anfangs keine custom.css, steam5.css in diesem ordner gab. Habe das manuell hinzugefügt/ersetzt, anfangs hat es 5.css überschrieben zum selben Inhalt wie steam5.css, aber beim 2. mal hat es dann die 5.css ausm Dracula Skin-Ordner übernommen.
Jedoch überschreibt Steam jedes mal nach einem Erfolgreichen Start mit dem Theme wieder die 5.css Datei.

Gefixxt ist das indem ich (für Autostart) mit **_Win+R_** eingebe: **_shell:startup_** und in den dadurch geöffneten Ordner einen Shortcut von Steam reinstelle welcher den Zusatz "**_-noveryfiles_**" hat. Dann geht auch per Autostart das Theme (für normalen Start muss man halt dann Steam per Shortcut öffnen (welcher den Zusatz hat), jedoch ist es etwas lästig wenn ich den Shortcut in der Taskleiste habe und dieser immer ein 2. Steam-Icon mit dem eigentlichen Client öffnet.

Dies hat es aber gefixxt, Steam ist da einfach doof drauf. Wär schön wenn es eine Möglichkeit gäbe das ohne solche Umwege zu fixxen.

**Comment by vengefulpinecone** [comment]
Hi there, I'm having a similar issue and I haven't been able to fix it. I translated what's been written above and followed the steps but I still have only the partial skin appearing. 
![steam pic 1](https://user-images.githubusercontent.com/77848724/135534461-9d32aa8d-6e01-49b8-a761-05b2d3c54161.PNG)
![steam pic 2](https://user-images.githubusercontent.com/77848724/135534466-ae27405a-d199-4d55-84c9-24c73baa5e0d.PNG)
.

**Comment by Rovetown** [comment]
DId you replace the files as I've written above (in english) and moved them accordingly?

If so, did you make a shortcut of steam and disabled autostart with steam?
If thats the case, you need to start steam with that shortcut and it shoudl work fine.

If not, then Steam is probably still being b*tchy about this...
