### ISSUE TITLE
How to install it with *the extended version* on macOS?

### ISSUE THREAD

**Issue by ZzNoah** [dracula/steam#25]
There is no `5.css` File or `Steam/steamui/css` Directory in Steam on macOS version.

**Comment by tintinmaster** [comment]
I pushed an update with new instructions and new file names. Could you try it out and report back if it works now?

**Comment by tintinmaster** [comment]
Closed due to inactivity

**Comment by ZzNoah** [comment]
Yes, it works now. Sorry for the inactivity. I didn't subscribe this issue. :(
