### ISSUE TITLE
Theme not working on newest Steam Version

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [dracula/steam#27]
![image](https://user-images.githubusercontent.com/13170204/139647949-c07e7cd7-dddc-46f9-b500-3fb6e47f774d.png)
Quite the important number of information on this screenshot, but I'll describe it.
- Installed and applied the Steam Skin *(you can notice the added Dracula entry if you hardly distinguish the color skins of the steam UI)*.
- Ran the install.sh script successfully. You can notice, on the bottom right, that the files were correctly modified. The added custom.css, the 5.css renamed to steam5.css to allow for both files to be loaded.
- Also, while the current opened `steam\steamui\css` folder, and files has been opened after Steam *(To confirm that Steam haven't verified those, and replaced those files), You can see the Library Interface hasn't been modified in any way. You can also notice, on the terminal on the top, that Steam has been properly started with the `-noverifyfiles` parameter.
- You can notice some theming errors in the logs, making me believe that the custom theme .css has something wrong. *(But I don't know if it is worth pointing just some CSS variables, or just as another nail in the coffin of people making Steam skins)*
```
Errors in friends/friendsdialog.res:
unknown color 'ClientTextColor' referenced by style key 'textcolor'
Errors in friends/friendsdialog.res:
Couldn't find color 'FriendsSearchBG' referenced in render fill comand 'fill( x0 + 2, y0 - 1, x1 + 2, y1 + 5, FriendsSearchBG )'
Error parsing 'render_bg' key in a style definition
Errors in friends/friendsdialog.res:
Couldn't find color 'FriendsSearchBG' referenced in render fill comand 'fill( x0, y0 + 1, x1, y1, FriendsSearchBG )'
Error parsing 'render_bg' key in a style definition
unknown color 'ClientTextColorDisabled' referenced by style key 'textcolor'
Installing breakpad exception handler for appid(steam)/version(1635476327)
Installing breakpad exception handler for appid(steam)/version(1635476327)
ExecCommandLine: "'/home/pm/.local/share/Steam/ubuntu12_32/steam' '-noverifyfiles' '%U'"
```

**Comment by koplo199** [comment]
Not working at all with the latest Steam version :'(

**Comment by Jetspectre** [comment]
Hello, would this be fixed soon or is there any workaround until a PR is made?

**Comment by tintinmaster** [comment]
It looks like the current version is broken.
It probably will not be fixed till after Christmas :disappointed:

**Comment by Jetspectre** [comment]
Thank you for the response, I wish you a Merry Christmas!

**Comment by koplo199** [comment]
@Jetspectre As a workaround you can use my [branch](https://github.com/koplo199/steam) if you don't mind the main color being purple instead of the current pink :) 
There's also a fix included which apply the theme to the initial loading page ;)

**Comment by PoorPocketsMcNewHold** [comment]
> @Jetspectre As a workaround you can use my [branch](https://github.com/koplo199/steam) if you don't mind the main color being purple instead of the current pink :) 
> There's also a fix included which apply the theme to the initial loading page ;)

Would have been a better idea to push request your changes, minor the aesthetics ones which differ from the dracula colorscheme.

**Comment by koplo199** [comment]
> Would have been a better idea to push request your changes, minor the aesthetics ones which differ from the dracula colorscheme.

Sure, but I'm honestly too lazy to do it.

**Comment by Jetspectre** [comment]
@koplo199 Many thanks, love the purple!

**Comment by tintinmaster** [comment]
@koplo199 I really like your changes, especially the loading page. Purple looks very good, and I even think now it's better fitting as an accent colour. So if you want, you can open a pull request and I will happily merge the changes :vampire: .

Merry Christmas :christmas_tree:

**Comment by koplo199** [comment]
@tintinmaster Awesome, I'm glad you like it!

Merry Christmas to you too :christmas_tree:
