### ISSUE TITLE
accent colors not showing

### ISSUE THREAD

**Issue by eyramsel** [dracula/steam#30]
I followed all the instructions for both basic and extended installations, however the accent colors do not appear. There is the Dracula button on the top left though. Not sure if the skin was also applied in the library section of Steam.

![image](https://user-images.githubusercontent.com/96175841/146185362-7ff120ef-db4b-4d7f-9fc0-18e771dfac01.png)

**Comment by tintinmaster** [comment]
The theme is currently not working, will fix it, but will take some time. See #27
