### ISSUE TITLE
Store, Library, Community bar is cut off

### ISSUE THREAD

**Issue by KurtisEdwards220** [dracula/steam#43]
The new steam update has messed up the theme to where you now can't see or click on anything in that bar. When I revert back to the default skin I can see and interact with them again.

**Comment by eight85** [comment]
I can confirm this as well on Linux and Windows installations.
![Screenshot_20230130_220817](https://user-images.githubusercontent.com/60632993/216675044-5fd03ef9-5367-4d34-9a8f-0771cc4c6ea0.png)

**Comment by AnotherAH** [comment]
i have the same problem
![image](https://user-images.githubusercontent.com/70831339/216767216-23ddab3e-8522-47c0-be26-834c1191270a.png)

**Comment by WolfyBoy20** [comment]
I also have the same problem

**Comment by LuceXReborn** [comment]
Same thing happens for me plus for some reason i dont see the purple or anything else

**Comment by georg3k** [comment]
Can confirm (Fedora 37)

**Comment by georg3k** [comment]
Library is also completely messed up
![image](https://user-images.githubusercontent.com/12208636/218180196-f56096e8-9a89-4699-a923-95173d0da533.png)

**Comment by eight85** [comment]
https://github.com/shaneMenzies/steam fixes the issue :+1:

**Comment by georg3k** [comment]
> https://github.com/shaneMenzies/steam fixes the issue +1

Thanks, it fixed the navbar, but the library page is still broken

**Comment by tintinmaster** [comment]
Currently, I'm in finals period, so I don't have time to look into it further. But it seems like I can't access the developer menu anymore, which will it make harder to fix it, but I will look again when my finals are over.

**Comment by georg3k** [comment]
No prob, good luck on your finals
