### ISSUE TITLE
Broken in Manjaro 

### ISSUE THREAD

**Issue by undyingdisciple** [dracula/steam#6]
When I apply the theme to Steam the menu is covered up by my username floating over it. Also, when I try to access my Library nothing is there except a tiny box in the top left-hand corner that I have tried to resize but it doesn't allow me.

**Comment by Trollwut** [comment]
could it be, that it's pretty much the same as in https://github.com/dracula/steam/issues/4 ?

I made this theme before the last big update. I don't have quite time to fix it for now, but it definetely needs a makeover. I hope I find some time for it soon.

**Comment by undyingdisciple** [comment]
Yes it is exactly like the problem you showed in #4. Thank you for responding. I certainly understand not having the time to fix it right away. Hopefully you get some free time soon enough.

**Comment by Trollwut** [comment]
Meanwhile you might want to edit it in Steam Customizer (and maybe share if you got a result) and hope they've already updated for the new design :)

http://editor.steamcustomizer.com/anqbr

**Comment by Trollwut** [comment]
I finally fixed it for the new Steam Library. More to that in this issue: https://github.com/dracula/steam/issues/7
