### ISSUE TITLE
Would love it, if you fix this theme

### ISSUE THREAD

**Issue by tintinmaster** [dracula/steam#7]
As you know, the theme is broken since the [Steam Library update](https://store.steampowered.com/libraryupdate). If you now can find the time to get it fixed, I would really appreciate that and would buy you a coffee.

Stay healthy!
tintinmaster

**Comment by zenorocha** [comment]
Any ideas @Trollwut?

**Comment by Trollwut** [comment]
It's the same as mentioned in https://github.com/dracula/steam/issues/6 and https://github.com/dracula/steam/issues/4

The process would be quite simple: Using Steam in WINE and using the tool to create the Steam skin. Then copy these skin files away. This is the created theme: http://editor.steamcustomizer.com/anqbr

I might find some time in the coming days, but if someone else is quicker, that would be nice too :)

**Comment by Trollwut** [comment]
Ok, I did it :)

**`master` branch has been updated for the new Steam Library!**

Please bear in mind that the used tool is in beta and the customization in the new Steam Library isn't as much as in the old library. But at least we now got Dracula colors as background and in the menus.

And, well, at least it's not broken anymore!

I clicked through a few things and couldn't find any big bugs. If someone finds any, please don't hesitate to open an issue :)

**Comment by tintinmaster** [comment]
Thank you my friend :)

Everything works fine now for me. Maybe I will try to improve the theme, if possible, in the next days.
